spring.application.name=testing-workshop
spring.datasource.url=jdbc:h2:mem:testing-workshop
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
workshop.certificates-directory=build/certificates
